#!/usr/bin/env bash
set -e

read -n1 -p "Press any key to confirm in virtual environment..."
echo
pip install robotpy-installer
robotpy-installer download-robotpy
robotpy-installer download-opkg python38-robotpy-ctre python38-robotpy-rev python38-numpy python38-robotpy-cscore
#robotpy-installer download-opkg python38-robotpy-cscore

read -n1 -p "Press any key once connected to the robot..."
echo
robotpy-installer install-robotpy
robotpy-installer install-opkg python38-robotpy-ctre python38-robotpy-rev python38-numpy python38-robotpy-cscore
#robotpy-installer install-opkg python38-robotpy-cscore
